#ifndef KEITHLEY4200_GLOBAL_H
#define KEITHLEY4200_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KEITHLEY4200_LIBRARY)
#  define KEITHLEY4200SHARED_EXPORT Q_DECL_EXPORT
#else
#  define KEITHLEY4200SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KEITHLEY4200_GLOBAL_H
