#ifndef AGILENTU25XX_GLOBAL_H
#define AGILENTU25XX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGILENTU25XX_LIBRARY)
#  define AGILENTU25XXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AGILENTU25XXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AGILENTU25XX_GLOBAL_H
