#ifndef SOURCEMETERUNIT_GLOBAL_H
#define SOURCEMETERUNIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOURCEMETERUNIT_LIBRARY)
#  define SOURCEMETERUNITSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOURCEMETERUNITSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOURCEMETERUNIT_GLOBAL_H
