#ifndef AGU25XXEXTENSIONBOX_GLOBAL_H
#define AGU25XXEXTENSIONBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AGU25XXEXTENSIONBOX_LIBRARY)
#  define AGU25XXEXTENSIONBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AGU25XXEXTENSIONBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AGU25XXEXTENSIONBOX_GLOBAL_H
